import type { FinancialHealthSnapshot } from '../../application/financialHealth'
import { financialHealthLabels, money } from './presentation'

export function FinancialHealthPanel({ health }: { health: FinancialHealthSnapshot }) {
  return <section className={`panel financial-health health-${health.status.toLowerCase()}`} aria-label="Saúde financeira"><div className="section-heading"><h2>Saúde financeira</h2><strong className="pill">{financialHealthLabels[health.status]}</strong></div>
    <div className="finance-transfer-summary"><div><small>Caixa atual</small><strong>{money(health.cash)}</strong></div><div><small>Saldo do mês</small><strong>{money(health.monthlyBalance)}</strong></div><div><small>Disponível para transferências</small><strong>{money(health.availableTransferBudget)}</strong></div><div><small>Projeção em 3 meses · estimativa</small><strong>{money(health.projection3)}</strong></div><div><small>Projeção em 6 meses · estimativa</small><strong>{money(health.projection6)}</strong></div><div><small>Folha / teto mensal</small><strong>{money(health.payroll.current)} / {money(health.payroll.budget)}</strong><span>{health.payroll.current > health.payroll.budget ? 'ACIMA DO LIMITE' : 'Dentro do limite'}</span></div></div>
    <p className="muted">Estimativa: patrocínio e Loja conhecidos ({money(health.monthlyIncome)}/mês) menos folha e manutenção atuais ({money(health.monthlyExpenses)}/mês), mantidos constantes. Não prevê bilheteria, premiações, transferências ou mudanças nos contratos.</p><p className="muted">Reserva de segurança: {money(health.reserve)}. Disponível = menor valor entre orçamento aprovado e caixa após reserva; situação crítica bloqueia compras.</p>
    {health.alerts.length > 0 && <ul className="financial-alerts" aria-label="Alertas financeiros">{health.alerts.map(alert => <li key={alert}>⚠ {alert}</li>)}</ul>}
    <h3>Últimos 3 meses · registros até hoje</h3><div className="table-scroll"><table><caption className="sr-only">Tendência financeira recente</caption><thead><tr>{['Mês', 'Receitas', 'Despesas', 'Saldo'].map(label => <th key={label} scope="col">{label}</th>)}</tr></thead><tbody>{health.recent.map(row => <tr key={row.month}><th scope="row">{row.month.slice(5)}/{row.month.slice(0, 4)}{!row.hasRecords && <small> · Sem registros</small>}</th><td>{money(row.income)}</td><td>{money(row.expenses)}</td><td>{money(row.balance)}</td></tr>)}</tbody></table></div>
  </section>
}
