import { useState } from 'react'
import type { PrototypeSession } from '../../application/prototypeSession'
import { facilityMonthlyTotals, facilityOverview, startFacilityUpgrade } from '../../application/clubFacilities'
import type { FacilityType } from '../../finance/facilities'
import { dateLabel, money } from '../components/presentation'
import { TrainingPanel } from '../components/TrainingPanel'
import { AcademyPanel } from '../components/AcademyPanel'

function FacilityArt({ type }: { type: FacilityType }) {
  const color = { TRAINING: '#a3d966', YOUTH: '#6db4ba', MEDICAL: '#d7d9cf', SHOP: '#d6b966', STADIUM: '#8e9ecb' }[type]
  return <svg className="facility-art" viewBox="0 0 160 88" aria-hidden="true" shapeRendering="crispEdges"><rect width="160" height="88" fill="#0c202a" /><rect y="70" width="160" height="18" fill="#264438" /><rect x="18" y="32" width="124" height="38" fill="#36535b" /><path d="M12 32v-8h136v8z" fill={color} /><rect x="67" y="49" width="25" height="21" fill="#0a1b24" />{[28, 46, 103, 121].map(x => <rect key={x} x={x} y="43" width="11" height="13" fill="#719c9a" />)}<rect x="75" y="13" width="10" height="12" fill="#6a8082" /><rect x="84" y="14" width="21" height="8" fill={color} />{type === 'MEDICAL' ? <path d="M75 34h10v6h6v9h-6v6H75v-6h-6v-9h6z" fill="#d46f66" /> : type === 'SHOP' ? <path d="M26 32h108v8H26zM32 32v8m16-8v8m16-8v8m16-8v8m16-8v8m16-8v8m16-8v8" fill={color} stroke="#1e3438" strokeWidth="5" /> : <rect x="26" y="72" width="107" height="9" fill="#477951" />}<rect x="10" y="55" width="5" height="21" fill="#8c9991" /><rect x="5" y="51" width="15" height="5" fill="#eadba7" /></svg>
}
export function FacilitiesPage({ session, onAction, onStadium }: { session: PrototypeSession; onAction: (operation: () => PrototypeSession) => boolean; onStadium: () => void }) {
  const facilities = facilityOverview(session)
  const totals = facilityMonthlyTotals(session, session.game.humanClubId!)
  const [confirmId, setConfirmId] = useState<string>()
  const [message, setMessage] = useState('')
  const [confirmError, setConfirmError] = useState('')
  const selected = facilities.find(item => item.id === confirmId)
  const busy = !!session.liveMatch || !!session.pendingMatch
  return <div className="facilities-page"><header><span className="eyebrow">Administração · Patrimônio do clube</span><h1>Estrutura do clube</h1><p className="muted">Invista hoje. Construa o futuro do seu clube.</p></header><div className="facility-summary panel"><span>Manutenção mensal<strong>{money(totals.maintenance)}</strong></span><span>Receita mensal da Loja<strong className="finance-income">{money(totals.income)}</strong></span><span>Obras em andamento<strong>{facilities.filter(item => item.construction).length}</strong></span></div>
    {message && <p role="status" className="notice">{message}</p>}
    <TrainingPanel session={session} onAction={onAction} />
    <AcademyPanel session={session} onAction={onAction} />
    <div className="facility-grid">{facilities.map(item => <section className={`panel facility-card ${item.construction ? 'in-construction' : ''}`} key={item.id}><FacilityArt type={item.type} /><div className="section-heading"><h2>{item.name}</h2><span className="pill">Nível {item.level} / {item.maxLevel}</span></div><div className="facility-levels" aria-label={`Nível ${item.level} de ${item.maxLevel}`}>{item.levels.map((_, index) => <span className={index < item.level ? 'active' : ''} key={index} />)}</div><small className="facility-status">{item.construction ? 'EM OBRAS' : item.level === item.maxLevel ? 'NÍVEL MÁXIMO' : 'OPERACIONAL'}</small><p className="muted">{item.description}</p><p className="facility-benefit">{item.benefit}</p><dl><dt>Manutenção atual</dt><dd>{money(item.current.maintenanceCents)}/mês</dd>{item.type === 'SHOP' && <><dt>Receita comercial ativa</dt><dd className="finance-income">{money(item.current.monthlyIncomeCents)}/mês</dd></>}{item.type === 'STADIUM' && <>{(() => { const stadium = session.stadiums.find(value => value.clubId === item.clubId)!; const works = stadium.sectors.filter(sector => sector.construction); return <><dt>Capacidade atual</dt><dd>{stadium.capacity.toLocaleString('pt-BR')} lugares</dd><dt>Setores em obras</dt><dd>{works.length ? works.map(sector => sector.name).join(', ') : 'Nenhum'}</dd></> })()}</>}</dl>{item.construction ? <div className="notice warning"><strong>EM OBRAS · Nível {item.construction.targetLevel}</strong><p>Início: {dateLabel(item.construction.startedAt)}<br />Conclusão: {dateLabel(item.construction.completionDate)}</p></div> : item.next ? <p>Próxima melhoria: <strong>{money(item.next.upgradeCostCents)}</strong> · {item.next.upgradeDays} {item.next.upgradeDays === 1 ? 'dia' : 'dias'}</p> : <p className="notice">NÍVEL MÁXIMO</p>}<div className="actions"><button disabled={busy || !!item.construction || !item.next} onClick={() => { setConfirmError(''); setConfirmId(item.id) }}>MELHORAR — {item.name}</button>{item.type === 'STADIUM' && <button onClick={onStadium}>ABRIR ESTÁDIO</button>}</div></section>)}</div>
    {selected?.next && <div className="modal-backdrop"><section className="panel facility-confirm" role="dialog" aria-modal="true" aria-label={`Confirmar melhoria — ${selected.name}`} onKeyDown={event => { if (event.key === 'Escape') setConfirmId(undefined) }}><span className="eyebrow">Confirmar investimento</span><h2>{selected.name} · Nível {selected.level} → {selected.level + 1}</h2><dl><dt>Custo imediato</dt><dd>{money(selected.next.upgradeCostCents)}</dd><dt>Duração</dt><dd>{selected.next.upgradeDays} {selected.next.upgradeDays === 1 ? 'dia' : 'dias'}</dd><dt>Manutenção atual</dt><dd>{money(selected.current.maintenanceCents)}/mês</dd><dt>Nova manutenção</dt><dd>{money(selected.next.maintenanceCents)}/mês</dd>{selected.type === 'SHOP' && <><dt>Receita após conclusão</dt><dd>{money(selected.next.monthlyIncomeCents)}/mês</dd></>}</dl><p>{selected.benefit}</p><p className="muted">O custo será pago agora. O nível só muda na conclusão da obra.</p>{confirmError && <p className="notice error" role="alert">{confirmError}</p>}<div className="actions"><button autoFocus onClick={() => setConfirmId(undefined)}>CANCELAR</button><button className="primary" onClick={() => { try { const next = startFacilityUpgrade(session, selected.id); if (onAction(() => next)) { setMessage(`Obra iniciada: ${selected.name}. Custo registrado em Finanças.`); setConfirmId(undefined) } } catch (cause) { setConfirmError(cause instanceof Error ? cause.message : 'Não foi possível iniciar a obra.') } }}>CONFIRMAR MELHORIA</button></div></section></div>}
  </div>
}
