import { useState } from 'react'
import type { PrototypeSession } from '../../application/prototypeSession'
import { saveStadiumPrices, stadiumExpansionOptions, stadiumOverview, startStadiumSectorExpansion } from '../../application/stadiumManagement'
import { CurrencyField } from '../components/CurrencyField'
import { formatCurrencyInputBRL, parseCurrencyBRL } from '../components/currency'
import { dateLabel, money } from '../components/presentation'
import { StadiumModel } from '../components/StadiumModel'

const number = new Intl.NumberFormat('pt-BR')
export function StadiumPage({ session, onAction }: { session: PrototypeSession; onAction: (operation: () => PrototypeSession) => boolean }) {
  const saved = stadiumOverview(session)
  const [prices, setPrices] = useState(() => saved.stadium.sectors.map(sector => formatCurrencyInputBRL(sector.priceCents)))
  const [selected, setSelected] = useState(saved.stadium.sectors[0].id)
  const [hovered, setHovered] = useState<string>()
  const [message, setMessage] = useState('')
  const [expansionError, setExpansionError] = useState('')
  const [expansionPending, setExpansionPending] = useState(false)
  let view = saved
  let priceError = ''
  try { view = stadiumOverview(session, { ...saved.stadium, sectors: saved.stadium.sectors.map((sector, index) => ({ ...sector, priceCents: parseCurrencyBRL(prices[index]) })) }) } catch (cause) { priceError = cause instanceof Error ? cause.message : 'Confira os preços.' }
  const dirty = saved.stadium.sectors.some((sector, index) => prices[index] !== formatCurrencyInputBRL(sector.priceCents))
  const locked = !!session.liveMatch || !!session.pendingMatch
  const index = Math.max(0, saved.stadium.sectors.findIndex(sector => sector.id === selected))
  const sector = saved.stadium.sectors[index]
  const expansion = stadiumExpansionOptions(session, sector.id)
  const estimate = view.estimate?.sectors.find(item => item.id === sector.id)
  const last = saved.last?.sectors.find(item => item.id === sector.id)
  return <div className="stadium-page stadium-management"><header className="stadium-heading"><div><span className="eyebrow">Administração · Estádio</span><h1>{saved.stadium.name}</h1><p className="muted">Sua casa. Sua torcida. Cada setor conta.</p></div><span className="pill">ESTÁDIO FICTÍCIO · 2026</span></header>
    <div className="stadium-top-metrics">{[
      { label: 'Capacidade total', value: number.format(saved.stadium.capacity), note: `${saved.stadium.sectors.length} setores` },
      { label: 'Público estimado', value: view.estimate ? number.format(view.estimate.attendance) : '—', note: view.estimate ? `${(view.estimate.occupancy * 100).toFixed(1)}% de ocupação` : 'Sem jogo em casa pendente' },
      { label: 'Receita estimada', value: view.estimate ? money(view.estimate.revenueCents) : '—', note: dirty ? 'Prévia do rascunho · não salvo' : 'Com os preços salvos' },
    ].map(item => <article className="panel" key={item.label}><small>{item.label}</small><strong>{item.value}</strong><span>{item.note}</span></article>)}</div>
    <form onSubmit={event => { event.preventDefault(); if (priceError) return; if (onAction(() => saveStadiumPrices(session, saved.stadium.sectors.map((item, slot) => ({ id: item.id, priceCents: parseCurrencyBRL(prices[slot]) }))))) setMessage('Preços salvos. A nova estimativa será usada nos próximos jogos.') }}>
      <div className="stadium-management-grid"><section className="panel stadium-model-panel"><div className="section-heading"><div><span className="eyebrow">Visão do estádio</span><h2>Mapa de setores</h2></div><span className="stadium-view-tag">2D / PIXEL ART</span></div><StadiumModel stadium={saved.stadium} selected={hovered ?? selected} onSelect={id => { setSelected(id); setHovered(undefined) }} onHover={setHovered} /><div className="stadium-sector-tabs" role="group" aria-label="Selecionar setor">{saved.stadium.sectors.map(item => <button key={item.id} type="button" aria-pressed={item.id === selected} onClick={() => { setSelected(item.id); setHovered(undefined) }}>{item.name}</button>)}</div><p className="muted stadium-model-help">Selecione uma arquibancada no mapa ou use os botões para gerenciar seu setor.</p></section>
      <section className="panel stadium-sector-editor" aria-label={`Gestão do setor ${sector.name}`}><span className="eyebrow">Setor selecionado · {index + 1} / {saved.stadium.sectors.length}</span><h2>{sector.name}</h2><p className="muted">{number.format(sector.capacity)} lugares · {((sector.capacity / saved.stadium.capacity) * 100).toFixed(0)}% do estádio</p>
        <div className="stadium-expansion-info"><h3>Capacidade e expansão</h3><p>Capacidade atual <strong>{number.format(sector.capacity)} lugares</strong></p><p>Limite do nível {expansion.stadiumLevel} <strong>{number.format(expansion.maximumCapacity)} lugares</strong></p>{sector.construction ? <div className="notice warning"><strong>EM OBRAS</strong><br />Conclusão: {dateLabel(sector.construction.completionDate)}<br />Após a obra: {number.format(sector.construction.targetCapacity)} lugares</div> : expansion.targetCapacity ? <><p>Próxima expansão <strong>{number.format(sector.capacity)} → {number.format(expansion.targetCapacity)} lugares</strong></p><p>Custo <strong>{money(expansion.costCents!)}</strong> · Prazo <strong>{expansion.days} {expansion.days === 1 ? 'dia' : 'dias'}</strong></p><p>Manutenção adicional <strong>{money(expansion.maintenanceCents!)}/mês</strong></p><button type="button" disabled={locked} onClick={() => { setExpansionError(''); setExpansionPending(true) }}>EXPANDIR SETOR</button></> : <p className="muted">Este setor já atingiu o limite do nível estrutural. Melhore o nível do Estádio para liberar nova expansão.</p>}</div>
        <CurrencyField label={`Preço — ${sector.name}`} required value={prices[index]} onChange={value => { setPrices(current => current.map((price, slot) => slot === index ? value : price)); setMessage('') }} /><small className="muted">Preço salvo: {money(sector.priceCents)}{dirty ? ' · Rascunho em edição' : ''}</small>
        <div className="stadium-occupancy"><div><small>Ocupação estimada</small><strong>{estimate ? `${(estimate.occupancy * 100).toFixed(1)}%` : '—'}</strong></div><meter min={0} max={sector.capacity} value={estimate?.attendance ?? 0} aria-label={`Ocupação estimada — ${sector.name}`} /><span>{estimate ? `${number.format(estimate.attendance)} / ${number.format(sector.capacity)} torcedores` : 'Sem partida em casa pendente'}</span></div>
        <dl className="stadium-sector-numbers"><div><dt>Receita estimada</dt><dd className="finance-income">{estimate ? money(estimate.revenueCents) : '—'}</dd></div><div><dt>Potencial com lotação</dt><dd>{priceError ? 'Confira o preço' : money(sector.capacity * parseCurrencyBRL(prices[index]))}</dd></div></dl>
        {estimate?.highPrice && <p className="notice warning">⚠ Preço elevado pode reduzir a ocupação.</p>}
        <div className="stadium-last-sector"><span className="eyebrow">Última partida confirmada</span>{last ? <p>{number.format(last.attendance)} torcedores<br /><strong>{money(last.revenueCents)}</strong> em bilheteria</p> : <p className="muted">A primeira história desta arquibancada ainda está por vir.</p>}</div>
      </section></div>
      <div className="panel stadium-next-home"><span className="stadium-next-icon" aria-hidden="true">▣</span><div><small className="eyebrow">Próximo jogo em casa</small>{view.nextMatch ? <strong>{session.teams.find(team => team.club.id === view.nextMatch!.awayClubId)?.club.name} <span className="muted">· {dateLabel(view.nextMatch.date)} · Rodada {view.nextMatch.round}</span></strong> : <strong>Nenhum jogo em casa pendente</strong>}<p className="muted">Estimativas fictícias. Preço, reputação, adversário, rodada e classificação influenciam o público; o total final pode variar.</p></div></div>
      {priceError && <p role="alert" className="notice error">{priceError}</p>}{locked && <p className="notice">Público e preços da partida já estão fixados. Confirme o resultado para salvar novos preços.</p>}{message && <p role="status" className="notice">{message}</p>}
        <footer className="panel stadium-price-actions"><div><strong>{dirty ? 'Há preços em rascunho' : 'Preços confirmados'}</strong><small>Alterações passam a valer ao salvar. Navegar para outra tela descarta o rascunho.</small></div><div className="actions"><button type="button" disabled={!dirty} onClick={() => { setPrices(saved.stadium.sectors.map(item => formatCurrencyInputBRL(item.priceCents))); setMessage('Rascunho descartado.') }}>DESCARTAR</button><button className="primary" type="submit" disabled={!dirty || !!priceError || locked}>SALVAR PREÇOS →</button></div></footer>
    </form>{expansionPending && expansion.targetCapacity !== undefined && <div className="modal-backdrop"><section className="panel facility-confirm" role="dialog" aria-modal="true" aria-label={`Confirmar expansão — ${sector.name}`}><span className="eyebrow">Obra do estádio</span><h2>Expandir {sector.name}</h2><p>{number.format(sector.capacity)} → {number.format(expansion.targetCapacity)} lugares</p><p>Investimento: <strong>{money(expansion.costCents!)}</strong></p><p>Prazo: <strong>{expansion.days} dias</strong></p><p>Manutenção adicional: <strong>{money(expansion.maintenanceCents!)}/mês</strong></p>{expansionError && <p role="alert" className="notice error">{expansionError}</p>}<div className="actions"><button onClick={() => setExpansionPending(false)}>CANCELAR</button><button className="primary" onClick={() => { try { if (onAction(() => startStadiumSectorExpansion(session, sector.id))) { setMessage(`Expansão de ${sector.name} iniciada.`); setExpansionPending(false) } } catch (cause) { setExpansionError(cause instanceof Error ? cause.message : 'Não foi possível iniciar a obra.') } }}>CONFIRMAR EXPANSÃO</button></div></section></div>}{saved.last && <section className="panel"><h2>Última bilheteria confirmada</h2><p>{number.format(saved.last.attendance)} torcedores · Ocupação {(saved.last.occupancy * 100).toFixed(1)}% · Receita {money(saved.last.revenueCents)}</p><p className="muted">Valores do mesmo lançamento exibido no Centro Financeiro.</p></section>}
  </div>
}
